### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by designgears** [Josh5/unmanic.plugin.create_stereo_audio_clone#1]
Is there a reason this plugin is missing from the current release?

**Comment by Josh5** [comment]
> Is there a reason this plugin is missing from the current release?

Because nobody tested it and reported back if it was working

**Comment by Josh5** [comment]
If you give it a go and run it against your library, let me know how it goes

**Comment by designgears** [comment]
Ahh, I do have it loaded, nothing in the interface alerted me that it wasn't working properly tho. Checked the logs and found this. 

> 2022-04-16T01:01:50:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception encountered while importing module 'create_stereo_audio_clone' - No module named 'create_stereo_audio_clone.lib.ffmpeg'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 144, in __load_plugin_module
    module_spec.loader.exec_module(plugin_import)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/.unmanic/plugins/create_stereo_audio_clone/plugin.py", line 29, in <module>
    from create_stereo_audio_clone.lib.ffmpeg import StreamMapper, Probe, Parser
ModuleNotFoundError: No module named 'create_stereo_audio_clone.lib.ffmpeg'

**Comment by Josh5** [comment]
> Ahh, I do have it loaded, nothing in the interface alerted me that it wasn't working properly tho. Checked the logs and found this. 
> 
> > 2022-04-16T01:01:50:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception encountered while importing module 'create_stereo_audio_clone' - No module named 'create_stereo_audio_clone.lib.ffmpeg'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 144, in __load_plugin_module
>     module_spec.loader.exec_module(plugin_import)
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/.unmanic/plugins/create_stereo_audio_clone/plugin.py", line 29, in <module>
>     from create_stereo_audio_clone.lib.ffmpeg import StreamMapper, Probe, Parser
> ModuleNotFoundError: No module named 'create_stereo_audio_clone.lib.ffmpeg'

That's interesting. It must have built wrong. I'll get it fixed this week and update it.

**Comment by Josh5** [comment]
Is this still an issue? I installed this plugin from a fresh install on its own and I could not reproduce this.

**Comment by Josh5** [comment]
Closing due to age of issue and lack of response
